setwd("~/R/ExData_Plotting1/")
arq<-read.csv("~/R/data/household_power_consumption.txt",sep=";")
arq$NewDateTime <- strptime(paste(arq$Date,arq$Time), "%d/%m/%Y %H:%M:%S")
feb2007<-arq[(arq$NewDate == "2007-02-01" | arq$NewDate == "2007-02-02"),]
par(mar=c(4,5,2,1))
plot(feb2007$NewDateTime,feb2007$Sub_metering_1,type="l",ylab="Global Active Power (kilowatts)",xlab="")
points(feb2007$NewDateTime,feb2007$Sub_metering_2,col="red",type="l")
points(feb2007$NewDateTime,feb2007$Sub_metering_3,col="blue",type="l")
legend("topright",text.font=1,lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_1"))
dev.copy(png,file="plot3.png")
dev.off()
